org: alphaprime8
app: short-my-nft
service: short-my-nft-api-dev

frameworkVersion: '3'

package:
  exclude:
    - ./venv/**
    - ./__pycache__/**
    - ./node_modules/**

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: python3.9

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-wsgi
  - serverless-python-requirements
